### PR TITLE
Clarify that anyone can participate in the project

### LINKED ISSUE #84: Casual contributor role not defined in GOVERNANCE
## What happened?

By reading the current [GOVERNANCE doc](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), one could think that even new contributors need to go through a nomination/voting process 

> New contributors may be self-nominated or nominated by existing contributors, and must be elected by a supermajority of that project’s maintainers

* What did you expect to happen?
It should be clearly stated that every form of casual contribution (first time PR, Issue, presentation, blog post, etc) makes someone a casual contributor who doesn't need to go through any nomination or voting process.

### PR DESCRIPTION
**Pull request by dmikusa-pivotal**
Adds an "Everyone" role to try and clarify that you do not need to be a "contributor" to contribute. It's just a perhaps unfortunate choice for the name of the role we've chosen for folks that regularly participate in the Paketo projects. Everyone can contribute, those with the contributor role contribute a lot.

Resolves #84

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
@davidmirror-ops Thoughts on this?

**Review by fg-j — APPROVED** [review]

**Comment by davidmirror-ops** [comment]
I was thinking of a `Casual contributor` role to effectively define 'Everyone'

And also to rename the `Contributor role` to `Core contributor`.

So, the contribution ladder will start from casual contributions, then becoming a more regular -core- contributor and then eventually a maintainer.

wdyt?

**Comment by davidmirror-ops** [comment]
We can also draw inspiration from the [CNCF Contributor ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) template

**Comment by loewenstein** [comment]
I actually like the "everyone" notion. Besides, it is also a defined role in the Cloud Foundry community repo https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md.

**Comment by dmikusa-pivotal** [comment]
Oh, happy coincidence there @loewenstein. I had picked "Everyone" because was the most inclusive word I could come up with. Even if I've never done anything for the project, I still know I fit in that category.

I like the table in the CFF roles. That is really easy to follow and for comparison purposes. If others like that too, I could make one for Paketo roles and submit in a separate PR.

**Comment by davidmirror-ops** [comment]
Oh @loewenstein that's a pretty clear role definition table!

Even for 'everyone' the requirements and privileges are crystal clear

**Comment by dmikusa-pivotal** [comment]
I added a summary table: https://github.com/paketo-buildpacks/community/blob/gh_issue_84/GOVERNANCE.md#summary

Thoughts?

**Comment by loewenstein** [comment]
You've got a copy & paste artifact left in the table.

> Member of the Cloud Foundry Slack workspace

**Comment by dmikusa-pivotal** [comment]
Thanks @loewenstein - fixed that.

**Comment by loewenstein** [comment]
Also, I am not sure I agree to the requirement to be nominated for steering committee by invitation of the steering committee. But that might be a more general governance thing and not an issue with the table itself.

**Comment by fg-j** [comment]
@dmikusa-pivotal any blockers to merging this?

**Comment by dmikusa-pivotal** [comment]
I think we are 👍. Ryan approved as well, so that's two of three steering committee members.

**Pull request merged**
